Netlogix:
  JobQueue:
    FastRabbit:

      supervisor:

        # Every queue gets its own program.
        # Available placeholders:
        #  __APPLICATION_NAME__      The value of the Netlogix.JobQueue.FastRabbit.supervisor.applicationName setting
        #  __QUEUE_NAME__   Name of the queue defined in Flowpack.JobQueue.common.queues
        #  __JOB_NAME__     A deterministic name based on __APPLICATION_NAME__ and __QUEUE_NAME__; cleand up to comply with Rabbit naming scheme
        #  __CONFIG_FILE__  Absolute file path to the JSON config file for the queue
        program:
          stdout_logfile: '/dev/stdout'
          stdout_logfile_maxbytes: 0
          stderr_logfile: '/dev/stderr'
          stderr_logfile_maxbytes: 0
          user: null
