Netlogix:
  JobQueue:
    FastRabbit:

      supervisor:

        # Should be different for every flow app on one Rabbit
        applicationName: '%FLOW_PATH_ROOT%'

        workerPool:
          # Supervisor will start a single low memory consumer for every queue but consumers will only spawn high
          # memory flow apps when worker slots are available
          numberOfWorkers: 16
          # Slot names are deterministic. Pointing multiple flow apps to a shared lock directory will cap the total
          # number of high memory worker processes for the whole group.
          lockFileDirectory: /tmp/fast-rabbit

        # All workers will be placed in a common supervisord group.
        # Groups get created on demand.
        # For explicit groups: See Netlogix.Supervisor.groups
        #
        # Available placeholders:
        #  __APPLICATION_NAME__  The value of the Netlogix.JobQueue.FastRabbit.supervisor.applicationName setting
        groupName: 'default'

        # Every queue gets its own program.
        #
        # Available placeholders:
        #  __APPLICATION_NAME__   The value of the Netlogix.JobQueue.FastRabbit.supervisor.applicationName setting
        #  __QUEUE_NAME__         Name of the queue defined in Flowpack.JobQueue.common.queues
        #  __JOB_NAME__           A deterministic name based on __APPLICATION_NAME__ and __QUEUE_NAME__, cleand up to comply with Rabbit naming scheme
        #  __CONFIG_FILE__        Absolute file path to the JSON config file for the queue
        #  __NUMPROCS__           Number of parallel processes for a particular listener, defined by Flowpack.JobQueue.common.queues.__QUEUE_NAME__.fastRabbit.numProcs
        program:
          command: 'bash -c "sleep 5 && exec ./bin/fast-rabbit < __CONFIG_FILE__"'
          process_name: '%(program_name)s_%(process_num)02d'
          numprocs: '__NUMPROCS__'
          startsecs: 35
          startretries: 25
          user: 'www-data'

#Flowpack:
#  JobQueue:
#    Common:
#      queues:
#        'some-queue-name':
#          className: t3n\JobQueue\RabbitMQ\Queue\RabbitQueue
#          generateSupervisorConfigForFastRabbit: true
#
#          fastRabbit:
#            numProcs: 2
