Netlogix:
  JobQueue:
    FastRabbit:

      supervisor:

        contextName: '%FLOW_PATH_ROOT%'

        workerPool:
          numberOfWorkers: 16
          lockFileDirectory: /tmp/fast-rabbit

        groupTemplate: |
          [group:backend-services-__CONTEXT__-consumers]
          programs=__PROGRAMS__
          priority=100

        programTemplate: |
          [program:__JOB_NAME__]
          command=bash -c "sleep 5 && exec ./bin/fast-rabbit < __CONFIG_FILE__"
          stdout_logfile=AUTO
          stderr_logfile=AUTO
          process_name=%(program_name)s_%(process_num)02d
          numprocs=1
          autostart=true
          autorestart=true
          startsecs=35
          startretries=25
          stopsignal=TERM
          stopwaitsecs=10
          user=www-data
          environment=FLOW_CONTEXT='%env:FLOW_CONTEXT%'
          directory=%FLOW_PATH_ROOT%

#Flowpack:
#  JobQueue:
#    Common:
#      queues:
#        'some-queue-name':
#          className: t3n\JobQueue\RabbitMQ\Queue\RabbitQueue
#          generateSupervisorConfigForFastRabbit: true
